from guizero import App, Text, Box

cuaso = App("Thoi khoa bieu")
cuaso.width = 425
cuaso.height = 265
cuaso.bg = "#c0dfea"
chu = Text(cuaso, "đây là thời khóa biểu của tôi")
chu.align = "top"
box1 = Box(cuaso, align = "left", border = True, height = "fill", width = 85)
box2 = Box(cuaso, align = "left", border = True, height = "fill", width = 85)
box3 = Box(cuaso, align = "left", border = True, height = "fill", width = 85)
box4 = Box(cuaso, align = "left", border = True, height = "fill", width = 85)
box5 = Box(cuaso, align = "left", border = True, height = "fill", width = 85)

thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
chuthu2 = Text(thu2, text = "THỨ 2", size = 17)
tiet1thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
montiet1thu2 = Text(tiet1thu2, text = "ngữ văn", size = 14)
tiet2thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
montiet2thu2 = Text(tiet2thu2, text = "tiếng Anh", size = 14)
tiet3thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
montiet3thu2 = Text(tiet3thu2, text = "GĐDP", size = 14)
tiet4thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
montiet4thu2 = Text(tiet4thu2, text = "HĐTN", size = 14)
tiet5thu2 = Box(box1, align = "top", border = True, height = 40, width = 85)
montiet5thu2 = Text(tiet5thu2, text = "chào cờ", size = 14)

thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
chuthu3 = Text(thu3, text = "THỨ 3", size = 17)
tiet1thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
montiet1thu3 = Text(tiet1thu3, text = "toán", size = 14)
tiet2thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
montiet2thu3 = Text(tiet2thu3, text = "toán", size = 14)
tiet3thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
montiet3thu3 = Text(tiet3thu3, text = "mĩ thuật", size = 14)
tiet4thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
montiet4thu3 = Text(tiet4thu3, text = "vật lí", size = 14)
tiet5thu3 = Box(box2, align = "top", border = True, height = 40, width = 85)
montiet5thu3 = Text(tiet5thu3, text = "địa lí", size = 14)

thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
chuthu4 = Text(thu4, text = "THỨ 4", size = 17)
tiet1thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
montiet1thu4 = Text(tiet1thu4, text = "lịch sử", size = 14)
tiet2thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
montiet2thu4 = Text(tiet2thu4, text = "ngữ văn", size = 14)
tiet3thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
montiet3thu4 = Text(tiet3thu4, text = "ngữ văn", size = 14)
tiet4thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
montiet4thu4 = Text(tiet4thu4, text = "địa lí", size = 14)
tiet5thu4 = Box(box3, align = "top", border = True, height = 40, width = 85)
montiet5thu4 = Text(tiet5thu4, text = "tiếng Anh", size = 14)

thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
chuthu5 = Text(thu5, text = "THỨ 5", size = 17)
tiet1thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
montiet1thu5 = Text(tiet1thu5, text = "sinh học", size = 14)
tiet2thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
montiet2thu5 = Text(tiet2thu5, text = "hóa học", size = 14)
tiet3thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
montiet3thu5 = Text(tiet3thu5, text = "ngữ văn", size = 14)
tiet4thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
montiet4thu5 = Text(tiet4thu5, text = "công nghệ", size = 13)
tiet5thu5 = Box(box4, align = "top", border = True, height = 40, width = 85)
montiet5thu5 = Text(tiet5thu5, text = "GDCD", size = 14)

thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
chuthu6 = Text(thu6, text = "THỨ 6", size = 17)
tiet1thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
montiet1thu6 = Text(tiet1thu6, text = "tiếng Anh", size = 14)
tiet2thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
montiet2thu6 = Text(tiet2thu6, text = "toán", size = 14)
tiet3thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
montiet3thu6 = Text(tiet3thu6, text = "toán", size = 14)
tiet4thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
montiet4thu6 = Text(tiet4thu6, text = "sinh học", size = 14)
tiet5thu6 = Box(box5, align = "top", border = True, height = 40, width = 85)
montiet5thu6 = Text(tiet5thu6, text = "HĐTN", size = 14)


cuaso.display()